struct NDArray {
    int idx;
    int[32] d;
}

generator void genNDArray(ref NDArray arr) {
    arr = new NDArray(
        idx = 0,
        d = { ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)
            , ??(2), ??(2), ??(2), ??(2)});
}

int nondet(ref NDArray h) {
    int ret = h.d[h.idx];
    h.idx++;
    return ret;
}

void prog(NDArray h, ref int x, ref int y, ref int z) {
    x = 0;
    y = 0;
    z = 0;
    while(nondet(h) != 0) {
        x = x + 2 * nondet(h);
        y = y + 4 * nondet(h);
        z = z + 8 * nondet(h);
    }
}