struct Array {
    int[8] d;
}

generator void genArray(ref Array arr) {
    arr = new Array();
    arr.d[0] = ??(2);
    arr.d[1] = ??(2);
    arr.d[2] = ??(2);
    arr.d[3] = ??(2);
    arr.d[4] = ??(2);
    arr.d[5] = ??(2);
    arr.d[6] = ??(2);
    arr.d[7] = ??(2);
}

void random_sort(int a0, int a1, int a2, int a3, int n, Array h1, Array h2, ref boolean sorted) {
    int[4] a = {a0, a1, a2, a3};

    if(a[0] <= a[1] && a[1] <= a[2] && a[2] <= a[3])
        {sorted = 1; return ;}

    for(int i=0;i<n;i++)
    {
        int t = a[h1.d[i]];
        a[h1.d[i]] = a[h2.d[i]];
        a[h2.d[i]] = t;

        if(a[0] <= a[1] && a[1] <= a[2] && a[2] <= a[3])
            {sorted = 1; return ;}
    }
    sorted = 0;
}